#![allow(ambiguous_glob_reexports, dead_code, unused_imports)]

#[cfg(feature = "test_utils")]
mod test_utils;

pub mod export {
    pub use _core::export::*;

    // main packages
    #[cfg(feature = "auth")]
    pub use _auth::export::*;
    #[cfg(feature = "authz")]
    pub use _authz::export::*;

    // others
    #[cfg(feature = "http")]
    pub use _http::export::*;
    #[cfg(feature = "rand_utils")]
    pub use _rand_utils::export::*;
    #[cfg(feature = "tracing")]
    pub use _tracing::export::*;
}

pub mod reexport {
    pub use _core::reexport::*;

    // main packages
    #[cfg(feature = "auth")]
    pub use _auth::reexport::*;
    #[cfg(feature = "authz")]
    pub use _authz::reexport::*;

    // others
    #[cfg(feature = "http")]
    pub use _http::reexport::*;
    #[cfg(feature = "rand_utils")]
    pub use _rand_utils::reexport::*;
    #[cfg(feature = "tracing")]
    pub use _tracing::reexport::*;
}

pub mod prelude {
    pub use _core::prelude::*;
    pub use maplit::*;

    // main packages
    #[cfg(feature = "auth")]
    pub use _auth::prelude::*;
    #[cfg(feature = "authz")]
    pub use _authz::prelude::*;

    // others
    #[cfg(feature = "http")]
    pub use _http::prelude::*;
    #[cfg(feature = "rand_utils")]
    pub use _rand_utils::prelude::*;
    #[cfg(feature = "tracing")]
    pub use _tracing::prelude::*;

    // testing
    #[cfg(feature = "test_utils")]
    pub use crate::test_utils::prelude::*;
}

#[cfg(not(any(feature = "postgres", feature = "mysql", feature = "sqlite")))]
compile_error!("should enable one of features: postgres, mysql, sqlite");

#[cfg(all(feature = "http", not(any(feature = "axum"))))]
compile_error!("should enable one of features: axum");

/// Include the schema generated by `grand_line_build::generate_schema()`.
/// Place this once in the file where `Query` and `Mutation` should be defined.
#[macro_export]
macro_rules! include_generated_schema {
    () => {
        include! { concat!(env!("OUT_DIR"), "/grand_line_schema.rs") }
    };
}
