[package]
name = "_utils_proc"
version = "0.0.0"
edition = "2024"

[lib]
name = "_utils_proc"
path = "lib.rs"
proc-macro = true

[dependencies]
_utils = { path = "../macro_utils", default-features = false, features = [] }
