[package]
name = "grand-line-proc-proc-macros"
version = "0.0.0"
edition = "2024"

[lib]
name = "grand_line_proc_proc_macros"
path = "lib.rs"
proc-macro = true

[dependencies]
quote = { version = "1.0.40" }
syn = { version = "2.0.104", features = ["full"] }
